### PR TITLE
Use a different method for ffmpeg frame count

### LINKED ISSUE #367: Encoding fails with "FRAME MISMATCH" when encoding with aomenc --enable-keyframe-filtering=2
This is likely due to the fact that keyframe filtering mode 2 is not supported by all decoders. Whatever decoder av1an is using is failing to decode the files.

I'll self-assign this and take a look.

### PR DESCRIPTION
**Pull request by shssoichiro**
This method uses ffprobe to count the number of packets
(which is identical to the number of frames, but faster)
in a video stream. This works with more video formats,
including with --enable-keyframe-filtering=2 in aomenc.
Performance should be similar or better than ffmpeg -copy.

Fixes #367

### CODE REVIEW

**Comment by shssoichiro** [comment]
I originally wrote that VS was still broken. That's wrong because av1an uses ffms2 instead of lsmash. I manually tested with lsmash because it was easier. 🤦‍♂️

**Comment by shssoichiro** [comment]
I want to finish through a full encode just to verify nothing else needs changed. 10min left.

**Comment by redzic** [comment]
Just putting this out there, but alternatively we can even statically link ffmpeg (using the `ffmpeg-next` crate) into av1an and get the frame count that way.

Here is an example program that does that (using `ffmpeg-next` 4.4.0):

```rust
use ffmpeg::format::input;
use ffmpeg::media::Type;
use std::env;

fn main() -> Result<(), ffmpeg::Error> {
    ffmpeg::init().unwrap();

    if let Ok(mut ictx) = input(&env::args().nth(1).expect("Cannot open file.")) {
        let input = ictx
            .streams()
            .best(Type::Video)
            .ok_or(ffmpeg::Error::StreamNotFound)?;
        let video_stream_index = input.index();

        let frames = ictx
            .packets()
            .filter(|(stream, _)| stream.index() == video_stream_index)
            .count();

        println!("{} frames", frames);
    }

    Ok(())
}
```

**Comment by shssoichiro** [comment]
@redzic I don't mind that. For the most part I prefer it to calling a program on the system, however it would increase compile times. So that might be worth a bigger discussion if we want to pull that crate in.

**Comment by shssoichiro** [comment]
Findings:

- ffmpeg concat method doesn't work at all. Resulting file is 500 bytes, doesn't play.
- ivf concat method produces a video file, but seeking is broken.
- mkvmerge concat method works and produces a playable, seekable file.

**Comment by shssoichiro** [comment]
I feel like getting ffmpeg's concat method to work with kf=2 will be harder than parsing the frame count. So for now I added a validation check to exit at the start of the encode if they're setting kf=2 and not using mkvmerge concat method.

File: av1an-core/src/project.rs [hunk 1]
```diff
@@ -387,6 +387,17 @@ impl Project {
       self.video_params = self.encoder.get_default_arguments();
     }
 
+    if self
+      .video_params
+      .iter()
+      .any(|param| param == "--enable-keyframe-filtering=2")
```
Comment (redzic) [inline av1an-core/src/project.rs:393]: I think we should skip this step if not using aomenc as the encoder

File: av1an-core/src/project.rs [hunk 2]
```diff
@@ -387,6 +387,18 @@ impl Project {
       self.video_params = self.encoder.get_default_arguments();
     }
 
+    if self.encoder == Encoder::aom
+      && self
+        .video_params
+        .iter()
+        .any(|param| param == "--enable-keyframe-filtering=2")
+      && self.concat != ConcatMethod::MKVMerge
```
Comment (redzic) [inline av1an-core/src/project.rs:395]: one more nitpick, `&&` evaluates left to right, so the check for mkvmerge should be before the param check for enable-kf=2 just to avoid comparing strings if it's not necessary

**Comment by redzic** [comment]
LGTM, although I remember @master-of-zen said he would prefer to use only the ffmpeg binary and not ffprobe when I mentioned this issue before with `--enable-keyframe-filtering=2`.

@master-of-zen how would you feel about pulling in ffmpeg-next?

**Comment by master-of-zen** [comment]
@shssoichiro @redzic Thank you both.
I don't like adding ffprobe as another dependency that is not integrated into av1an. That's the primary reason why I gave favor to FFmpeg frame counting.
I feel totally fine with adding `ffmpeg-next`, as it's statically linked, and I don't need to expect from end-user to have the correct version of it that builds correctly.
And I like the idea of integrating into av1an instead of relaying on third-party packages, which can vary tremendously.
I'm not adamant about gatekeeping ffprobe, I would like to continue without adding it.
That's how I see it

**Comment by shssoichiro** [comment]
I'm fine with going the ffmpeg-next route. Follow-up question: Do we want to try and replace all calls to ffmpeg with the ffmpeg-next crate? I think that would help as it cuts out that entire external dependency.

**Comment by master-of-zen** [comment]
@shssoichiro That would be aaaaaamazing :)

**Comment by redzic** [comment]
@shssoichiro Ideally we would, but for this PR you can change just `num_frames`. We can incrementally port the rest of the calls to ffmpeg.

**Comment by shssoichiro** [comment]
Cool, I can do that as a followup PR then. Since I have nothing better to do right now 😅

File: av1an-core/Cargo.toml [hunk 3]
```diff
@@ -44,6 +44,10 @@ path_abs = "0.5.1"
 av-scenechange = "0.7.0"
 y4m = "0.7.0"
 
+[dependencies.ffmpeg-next]
```
Comment (redzic) [inline av1an-core/Cargo.toml:47]: Can we use ffmpeg-next but refer to it as ffmpeg by changing the package name in cargo? Specify the dependency as ffmpeg but add a property `package = "ffmpeg-next"`

Comment (shssoichiro) [reply av1an-core/Cargo.toml:47]: I attempted that, and it was easier to just use `ffmpeg_next` because we have a module called `ffmpeg` in av1an and that becomes confusing to both devs and the compiler.

**Comment by shssoichiro** [comment]
Oh... That broke CI. 😬

File: av1an-core/Cargo.toml (hunk 3 above)
Comment (redzic) [reply av1an-core/Cargo.toml:47]: ah I see, makes sense. what do you think of calling it `avcodec` then, or do you prefer `ffmpeg_next`?

Comment (shssoichiro) [reply av1an-core/Cargo.toml:47]: I'm not a fan of using `avcodec` since technically that's just one part of ffmpeg. I also don't love how `ffmpeg_next` is kind of verbose, but I'm not sure of a great way to shorten it. 🤔

Comment (redzic) [reply av1an-core/Cargo.toml:47]: I know there's another crate called `ffav` (but then, it might be confused since we are not actually using that package). But for now, I guess we can just keep it as `ffmpeg_next`

**Comment by shssoichiro** [comment]
I had to enable the "build" feature in ffmpeg to get the CI to pass... I'm going to try a couple more things to see if I can get it to work without that, because that does slow down the builds considerably.

**Comment by redzic** [comment]
For some reason the without the `build` feature, ffmpeg doesn't seem to actually get linked statically.

Some comparisons of binary size of the program to get the frame count posted earlier:


|              | with debug symbols | stripped  |
|--------------|--------------------|-----------|
| build+static | 104.56 MB          | 20.96 MB  |
| static       | 3.44 MB            | 294.91 KB |

Maybe we could add a cargo feature to control if ffmpeg gets linked dynamically or statically, and link it dynamically in CI?

**Comment by shssoichiro** [comment]
Which would it make more sense to use as the default, static or dynamic?

**Comment by redzic** [comment]
Maybe we should statically link it by default, since the entire point of pulling this crate in is to remove runtime dependencies. I think we would mostly use static linking for releases, and dynamic linking for doing local builds and for the CI.

**Comment by shssoichiro** [comment]
It looks like there's no capability in Cargo to set features per profile (e.g. automatically use static linking for release builds). That would have been nice. Given that, I wonder if it still makes sense to statically link, because that would be enabled for dev builds by default? (We can easily control CI with CLI args, so I'm not too concerned about that, it's more about developer + user experience.)

**Comment by redzic** [comment]
From a user experience, it would be easiest if they could just do `cargo build --release` and it statically links everything by default. Also, while we're at it, can we set only `av-scenechange` to compile with maximum optimizations for debug builds?

And from a developer experience, it would be easier for it to dynamically link by default. On my machine for the example program posted earlier, incremental static builds took 2.37s and incremental dynamic builds took 0.74s.

> It looks like there's no capability in Cargo to set features per profile (e.g. automatically use static linking for release builds)

That is unfortunate, because I feel like the perfect solution if cargo could do that would have been to set `av-scenechange` to compile with opt-level=3 for both debug and release builds, and statically link on release builds by default and dynamically link on debug builds.

**Comment by shssoichiro** [comment]
We can set opt-level on a per-crate and per-profile basis, so that is possible for av-scenechange. However, profiles do not support changing features, so automatically switching between dynamic and static is not possible as far as I'm aware.

**Comment by shssoichiro** [comment]
I decided to make static the default, and I disabled it for CI builds (so they will use dynamic). I think that's the better option for compatibility, given the goal was to remove an external dependency. Devs can always use the dynamic build with `cargo build --no-default-features`.

**Comment by shssoichiro** [comment]
I remembered why the CI was originally failing. The version of ffmpeg in the docker image is too old and can't decode AV1 (or at least that's what it seems). So we will have to use the static version in CI, it seems.

**Comment by shssoichiro** [comment]
This is ready for any final feedback now.

**Comment by redzic** [comment]
LGTM, @master-of-zen ?

**Comment by master-of-zen** [comment]
@shssoichiro @redzic Amazing :rocket:

**Comment by redzic** [comment]
Ah, the only thing actually was that the commit message is out of date now, it still says that it uses ffprobe
